### PR TITLE
Sonar

### LINKED ISSUE #44: Sonar Support
We just need to implement a sonar.

### PR DESCRIPTION
**Pull request by superjax**
Added support for Sonar Closes #44

### CODE REVIEW

**Comment by superjax** [comment]
I don't know why it says that it's failing the build.  It works on my computer, flashes and runs just fine

**Comment by superjax** [comment]
Ahah, Bad submodule reference.  oops!

**Comment by dpkoch** [comment]
Sweet!

**Comment by dpkoch** [comment]
Sweet!

**Pull request merged**
